services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    